### ISSUE TITLE
/usr/bin/ld cannot find -lasio

### ISSUE THREAD

**Issue by DPontes** [platisd/break-the-dependency-cpp#2]
**Error Output:**

```[ 33%] Built target asio_serial_port_manager
[ 66%] Built target camera_power_controller
[ 83%] Linking CXX executable src_main
/usr/bin/ld: cannot find -lasio
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/src_main.dir/build.make:86: src_main] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/src_main.dir/all] Error 2
make: *** [Makefile:84: all] Error 2 
```

**Prerequisites for error replication:**

- Added: `set(CMAKE_CXX_STANDARD 17)` to `/src/CMakelists.txt` due to compilation errors due to issues with `filesystem` lib
- Installed `sudo apt install libasio-dev`

**How to reproduce:**

`cmake .. && make`

**What was tried:**
- Searching Stackoverflow and the [Asio documentation](https://think-async.com/Asio/Documentation.html)
- checked the output of `dpkg -L libasio-dev` to see where the libasio could be installed, no luck
- checked the output of `ld -lasio --verbose`, indicates that `ld: cannot find -lasio`

**Specs:**
- Ubuntu 20.04
- CMake 3.16.3
- Make 4.2.1

**Comment by platisd** [comment]
You shouldn't need to link anything as `asio` is intended to be used as a header-only library that is distributed [together](https://github.com/platisd/break-the-coupling-cpp/tree/master/external/asio-1-18-0) with this project. In other words, you should not need to install anything by yourself or link. What happens if you uninstall `libasio-dev`? Perhaps that's what's messing things up?

You can check out the [CI configuration](https://github.com/platisd/break-the-coupling-cpp/blob/master/.github/workflows/examples-ci.yml) to see how the project's built.

**Comment by DPontes** [comment]
**SOLVED: Issue was PEBCAC**

**Description**: Based on the CI configuration files, I noticed that the build and make must be done in the "main" directory of the project, and not, as I was doing, in the `~/break-the-coupling-cpp/src/build/` directory.


**Additional Notes:**

(notes written previous to solution above being found)
After removing `libasio-dev`, removing `build/` and redoing `cmake .. && make` there's the error:
```
/include/AsioSerialPortManager.h:7:10: fatal error: asio.hpp: No such file or directory
    7 | #include <asio.hpp>
       |               ^~~~~~~~~~ 
compilation terminated.
```

After seeing this error previously, I assumed that there was an issue with `Asio` dependencies. Looking around, it seemed that this could be installed separately from the `boost` library which I thought you'd have assumed the user would have had already installed locally.

From the [CI configuration](https://github.com/platisd/break-the-coupling-cpp/blob/master/.github/workflows/examples-ci.yml) file, I see that the `libcurl4-openssl-dev` which I have installed but still get the same result..
